Khurshid Abdulla
2407067


**4.1 Exercise on Functions:**

**Task - 1:**

In [ ]:

def length_conversion():
    print("1: m to ft")
    print("2: ft to m")
    try:
        op = int(input("choose 1 or 2 \t"))
        if op == 1:
            conv = float(input("Enter a number for conversion \t"))
            print(conv * 3.28084, "ft")
        elif op == 2:
            conv = float(input("Enter a number for conversion \t"))
            print(conv / 3.28084, "m")
        else:
            print("Enter a valid number")
    except ValueError:
        print("Invalid input! Please enter a numeric value.")


def weight_conversion():
    print("1: kg to lbs")
    print("2: lbs to kg")
    try:
        op = int(input("choose 1 or 2 \t"))
        if op == 1:
            conv = float(input("Enter a number for conversion \t"))
            print(conv * 2.20462, "lbs")
        elif op == 2:
            conv = float(input("Enter a number for conversion \t"))
            print(conv / 2.20462, "kg")
        else:
            print("Enter a valid number")
    except ValueError:
        print("Invalid input! Please enter a numeric value.")


def volume_conversion():
    print("1: L to gal")
    print("2: gal to L")
    try:
        op = int(input("choose 1 or 2 \t"))
        if op == 1:
            conv = float(input("Enter a number for conversion \t"))
            print(conv * 0.264172, "gal")
        elif op == 2:
            conv = float(input("Enter a number for conversion \t"))
            print(conv / 0.264172, "L")
        else:
            print("Enter a valid number")
    except ValueError:
        print("Invalid input! Please enter a numeric value.")

try:
    a = int(input("1: length 2: weight 3: volume \t"))
    if a == 1:
        length_conversion()
    elif a == 2:
        weight_conversion()
    elif a == 3:
        volume_conversion()
    else:
        print("Enter a valid number")
except ValueError:
    print("Invalid input! Please enter a numeric value.")


1: length 2: weight 3: volume 	1
1: m to ft
2: ft to m
choose 1 or 2 	1
Enter a number for conversion 	1000
3280.84 ft


**Task - 2:**

In [ ]:


def sum(numbers):
    total = 0
    for num in numbers:
        total += num
    return total
def average(numbers):
    return sum(numbers) / len(numbers)
def maximum(numbers):
    maximum = numbers[0]
    for num in numbers:
        if num > maximum:
            maximum = num
    return maximum
def minimum(numbers):
    minimum = numbers[0]
    for num in numbers:
        if num < minimum:
            minimum = num
    return minimum
print("Choose an operation:")
print("1: Sum | 2: Average | 3: Maximum | 4: Minimum")
try:
    choice = int(input("Enter your choice (1-4): "))
    user_input = input("Enter numbers separated by spaces: ")
    numbers = [float(x) for x in user_input.split()]
    if choice == 1:
              print("Sum:", sum(numbers))
    elif choice == 2:
                print("Average:", average(numbers))
    elif choice == 3:
                print("Maximum:", maximum(numbers))
    elif choice == 4:
                print("Minimum:", minimum(numbers))
    else:
        print("Error: Enter a valid number (1-4).")
except ValueError:
    print("Error: Invalid input. Please enter numbers correctly.")

**4.2 Exercise on List Manipulation:**

**1. Extract Every Other Element:**

In [ ]:

def extract_every_other(b):
  c=b[::2]
  print(c)
x=input("enter a list of number \t")
b=[int(a) for a in x.split()]
extract_every_other(b)

enter a list of number 	1 2 3
[1, 3]


**2. Slice a Sublist:**

In [ ]:


def get_sublist(a, b, c):
  d=[]
  i=0
  while i<=c:
    if a[i] in range(b,c):
      d.append(a[i])
    i=i+1
  print(d)
no=input("enter numbers with space \t")
a=[int(x) for x in no.split()]
b=int(input("enter the starting no for the list \t"))
c=int(input("enter the ending no for the list \t"))
get_sublist(a,b,c)

enter numbers with space 	1 2 3 4 5
enter the starting no for the list 	2
enter the ending no for the list 	4
[2, 3]


**3. Reverse a List Using Slicing:**

In [ ]:
def reverse_list(lst):
  b=[]
  i=len(lst)-1
  while i>=0:
    b.append(lst[i])
    i=i-1
  print(b)
no=input("enter the no with spaces \t")
a=[int(x) for x in no.split()]
reverse_list(a)

enter the no with spaces 	1 2 3 4 5 6
[6, 5, 4, 3, 2, 1]


**4. Remove the First and Last Elements:**

In [ ]:

def remove_first_last(lst):
  b=lst[1:len(lst)-1]
  print(b)
no=input("enter no with space")
a=[int(x) for x in no.split()]
remove_first_last(a)

enter no with spaces1 2 3 4
[2, 3]


**5. Get the First n Elements:**

In [ ]:

def get_first_n(lst,n):
  print(lst[0:n])
no=input("enter no with space \t")
a=[int(x) for x in no.split()]
b=int(input("enter the last element no \t"))
get_first_n(a,b)

enter no with space 	1 2 3 4 5
enter the last element no 	3
[1, 2, 3]


**6. Extract Elements from the End:**

In [ ]:

def get_last_n(lst,n):
  print(lst[-n:])
no=input("enter no with space \t")
a=[int(x) for x in no.split()]
b=int(input("enter the last element no \t"))
get_last_n(a,b)

enter no with space 	1 2 3 4 5
enter the last element no 	2
[4, 5]


**7. Extract Elements in Reverse Order:**

In [ ]:

def reverse_skip(lst,n):
  print(lst[-n::-2])
no=input("enter no with space \t")
a=[int(x) for x in no.split()]
b=int(input("enter the last element no \t"))
reverse_skip(a,b)

enter no with space 	1 2 3 4 5
enter the last element no 	3
[3, 1]


4.3 Exercise on Nested List:

**1. Flatten a Nested List:**

In [ ]:

def flatten(lst):
  d=[]
  for b in lst:
    for c in b:
      d.append(c)
  print(d)
lst=[[1, 2], [3, 4], [5]]
flatten(lst)

[1, 2, 3, 4, 5]


**2. Accessing Nested List Elements:**

In [ ]:
lst=[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
a=int(input("enter the 1st index"))
b=int(input("enter the 2nd index"))
print(lst[a][b])

enter the 1st index1
enter the 2nd index2
6


**3. Sum of All Elements in a Nested List:**

In [ ]:

def sum_nested(lst):
  sum = 0
  for x in lst:
    if isinstance(x,list):
      for y in x:
        if isinstance(y,list):
          for z in y:
            sum = sum + z
        else:
          sum = sum + y
    else:
      sum = sum + x
  print(sum)
lst = [[1, 2], [3, [4, 5]], 6]
sum_nested(lst)

21


**4. Remove Specific Element from a Nested List:**

In [ ]:

def remove(lst,n):
  b=[]
  for x in lst:
    if isinstance(x, list):
      b.append(remove(x, n))
    else:
      if x != n:
        b.append(x)
  return(b)
a = [[1, 2], [3, [4, 5]], 6]
print(remove(a,2))

[[1], [3, [4, 5]], 6]


**5. Find the Maximum Element in a Nested List:**

In [ ]:

def find_max(lst):
  b=0
  for x in lst:
    if isinstance(x,list):
      for y in x:
        if isinstance(y, list):
          for z in y:
            if z>b:
              b=z
        else:
          if y>b:
            b=y
    else:
      if x>b:
        b=x
  print(b)
a = [[1, 2], [3, [4, 5]], 6]
find_max(a)

6


**6. Count Occurrences of an Element in a Nested List:**

In [ ]:

def count_occurance(lst, n):
  temp=0
  for x in lst:
    if isinstance(x, list):
      for y in x:
        if isinstance(y,list):
          for z in y:
            if z==n:
              temp=temp+1
        else:
          if y==n:
            temp=temp+1
    else:
      if x==n:
        temp=temp+1
  print(temp)
a = [[1, 2], [2, 3], [2, 4]]
n=2
count_occurance(a,n)

3


**7. Flatten a List of Lists of Lists:**

In [ ]:

def deep_flatten(lst):
  b=[]
  for x in a:
    if isinstance(x,list):
      for y in x:
        if isinstance(y,list):
          for z in y:
            b.append(z)
        else:
          b.append(y)
    else:
      b.append(x)
  print(b)
a=[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
deep_flatten(a)

[1, 2, 3, 4, 5, 6, 7, 8]


**8. Nested List Average:**

In [ ]:

def average_nested(lst):
  b=0
  i=0
  for x in a:
    if isinstance(x,list):
      for y in x:
        if isinstance(y,list):
          for z in y:
            b=b+z
            i=i+1
        else:
          b=b+y
          i=i+1
    else:
      b=b+x
      i=i+1
  print(b/i)
a=[[1, 2], [3, 4], [5, 6]]
average_nested(a)

3.5


**10 To - Do - NumPy**

**10.1 Basic Vector and Matrix Operation with Numpy.**

**Problem - 1: Array Creation:**

In [ ]:
import numpy as np
# 1. Initialize an empty array with size 2X2.
print("this is the empty set")
print(np.empty((2,2)))
# 2. Initialize an all one array with size 4X2.
print("this is the ones set")
print(np.ones((4,2)))
# 3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
print("this is the custom set")
print(np.full((2,2),2))
# 4. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}
nlst=[[1, 2, 3], [4, 5, 6]]
lst=np.array(nlst)
print("this is conversion to array")
print(lst)
# 5. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
print("this is the converesion to zero set")
print(np.zeros_like(lst))
# 6. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
print("this is the converesion to one set")
print(np.ones_like(lst))

this is the empty set
[[1.e-323 1.e-323]
 [1.e-323 1.e-323]]
this is the ones set
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
this is the custom set
[[2 2]
 [2 2]]
this is conversion to array
[[1 2 3]
 [4 5 6]]
this is the converesion to zero set
[[0 0 0]
 [0 0 0]]
this is the converesion to one set
[[1 1 1]
 [1 1 1]]


**Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:**

In [ ]:
import numpy as np
# 1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
print("this is array printing from start to end")
print(np.arange(10,50))
# 2. Create a 3X3 matrix with values ranging from 0 to 8.
print("this is array printing from start to end with custom shape")
print(np.arange(0,9).reshape(3,3))
# 3. Create a 3X3 identity matrix.{Hint:np.eye()}
print("this is identical matrix of 3 X 3")
print(np.eye(3,3))
# 4. Create a random array of size 30 and find the mean of the array.
n=30
a=np.arange(n)
print("thisis the mean",a.mean()/n)
# 5. Create a 10X10 array with random values and find the minimum and maximum values.
tenmatrix=np.arange(100).reshape(10,10)
print("minimum value",tenmatrix.min())
print("maximum value",tenmatrix.max())
# 6. Create a zero array of size 10 and replace 5th element with 1.
zerolst=np.zeros(10)
zerolst[4]=1
print("this is modified zero list",zerolst)
# 7. Reverse an array arr = [1,2,0,0,4,0].
arr= [1,2,0,0,4,0]
newarr=np.array(arr)
print("this is the reverse new list")
print(newarr[::-1])
# 8. Create a 2d array with 1 on border and 0 inside.
borderlst=np.ones((5,5))
borderlst[1:-1,1:-1]=0
print("this is the border 1 and inside 0 list")
print(borderlst)
# 9. Create a 8X8 matrix and fill it with a checkerboard pattern.
check=np.full((8,8),"0")
check[0::2,1::2]="1"
check[1::2,0::2]="1"
print("this is the checkboard pattern")
print(check)

this is array printing from start to end
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
this is array printing from start to end with custom shape
[[0 1 2]
 [3 4 5]
 [6 7 8]]
this is identical matrix of 3 X 3
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
thisis the mean 0.48333333333333334
minimum value 0
maximum value 99
this is modified zero list [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
this is the reverse new list
[0 4 0 0 2 1]
this is the border 1 and inside 0 list
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
this is the checkboard pattern
[['0' '1' '0' '1' '0' '1' '0' '1']
 ['1' '0' '1' '0' '1' '0' '1' '0']
 ['0' '1' '0' '1' '0' '1' '0' '1']
 ['1' '0' '1' '0' '1' '0' '1' '0']
 ['0' '1' '0' '1' '0' '1' '0' '1']
 ['1' '0' '1' '0' '1' '0' '1' '0']
 ['0' '1' '0' '1' '0' '1' '0' '1']
 ['1' '0' '1' '0' '1' '0' '1' '0']]


**Problem - 3: Array Operations:**

In [ ]:
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
print("this is addition of 2 array")
print(x+y)
print("this is subtraction of 2 array")
print(x-y)
print("this is product of x array with 5")
print(x*5)
print("this is square of x array")
print(x*x)
print("this is dot product of x any v array",np.dot(x,v))
print("this is dot product of v any w array",np.dot(v,w))
print("this is dot product of x any y array",np.dot(x,y))
print(np.concatenate((x, y)))
print(np.vstack((v, w)))
# print(np.concatenate((x, v)))
print("concadination of the x and v is not possible cause")
print("all the input arrays must have same number of dimensions, \nbut the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)")

this is addition of 2 array
[[ 6  8]
 [10 13]]
this is subtraction of 2 array
[[-4 -4]
 [-4 -3]]
this is product of x array with 5
[[ 5 10]
 [15 25]]
this is square of x array
[[ 1  4]
 [ 9 25]]
this is dot product of x any v array [29 77]
this is dot product of v any w array 219
this is dot product of x any y array [[19 22]
 [50 58]]
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 10]
 [11 12]]
concadination of the x and v is not possible cause
all the input arrays must have same number of dimensions, 
but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


**Problem - 4: Matrix Operations:**

In [ ]:
import numpy as np
a = np.array([[3,4],[7,8]])
newa=np.linalg.inv(a)
b = np.array([[5,3],[2,1]])
d=np.dot(a,newa)
print("A X A^-1 = I")
print(d.astype(int))
print("\nAB",np.dot(a,b))
print("BA",np.dot(b,a))
print("So AB!=BA")
print(np.dot(a,b).T)
print(np.dot(b.T,a.T))
print("AB^T=B^TA^T")
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3,  1, -1]])
B = np.array([-1, -3, 9])
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
print("\n Matrix A:\n", A)
print("\nInverse of A:\n", A_inv)
print("\nSolution (x, y, z):\n", X)


A X A^-1 = I
[[1 0]
 [0 0]]

AB [[23 13]
 [51 29]]
BA [[36 44]
 [13 16]]
So AB!=BA
[[23 51]
 [13 29]]
[[23 51]
 [13 29]]
AB^T=B^TA^T

 Matrix A:
 [[ 2 -3  1]
 [ 1 -1  2]
 [ 3  1 -1]]

Inverse of A:
 [[ 0.05263158  0.10526316  0.26315789]
 [-0.36842105  0.26315789  0.15789474]
 [-0.21052632  0.57894737 -0.05263158]]

Solution (x, y, z):
 [ 2.  1. -2.]


**10.2 Experiment: How Fast is Numpy?**

**1. Element-wise Addition:**

In [ ]:
import time
import numpy as np
lst1= list(range(1000000))
lst2= list(range(1000000))
arr1=np.array(lst1)
arr2=np.array(lst2)
a=time.time()
c=lst1+lst2
b=time.time()
print("time taken by normal list calculation", b-a)
d=time.time()
f=arr1+arr2
e=time.time()
print("time taken by numpy", e-d)

time taken by normal list calculation 0.047866106033325195
time taken by numpy 0.003756284713745117


**2. Element-wise Multiplicatio**

In [ ]:
import time
import numpy as np
lst1= list(range(1000000))
lst2= list(range(1000000))
arr1=np.array(lst1)
arr2=np.array(lst2)
start=time.time()
c=[a * b for a, b in zip(lst1, lst2)]
end=time.time()
print("time taken by normal list calculation", end-start)
d=time.time()
f=arr1*arr2
e=time.time()
print("time taken by numpy", e-d)

time taken by normal list calculation 0.06711387634277344
time taken by numpy 0.0023620128631591797


**3. Dot Product**

In [ ]:
import time
import numpy as np
lst1= list(range(1000000))
lst2= list(range(1000000))
arr1=np.array(lst1)
arr2=np.array(lst2)
start=time.time()
c = sum(a * b for a, b in zip(lst1, lst2))
end=time.time()
print("time taken by normal list calculation", end-start)
d=time.time()
f=np.dot(arr1,arr2)
e=time.time()
print("time taken by numpy", e-d)


time taken by normal list calculation 0.08186125755310059
time taken by numpy 0.0018057823181152344


**4. Matrix Multiplication**

In [ ]:
import time

n = 1000

# Create two 1000x1000 matrices using lists
A = [[i for i in range(n)] for _ in range(n)]
B = [[j for j in range(n)] for _ in range(n)]

# Matrix multiplication with lists
start = time.time()
result_list = [[sum(A[i][k] * B[k][j] for k in range(n)) for j in range(n)] for i in range(n)]
end = time.time()

print("Time taken with Python lists:", end - start, "seconds")


KeyboardInterrupt: 

In [ ]:
import numpy as np
import time

# Create two 1000x1000 matrices using NumPy
n = 1000
A = np.arange(n*n).reshape(n, n)
B = np.arange(n*n).reshape(n, n)

# Matrix multiplication with NumPy
start = time.time()
result_array = np.dot(A, B)   # or A @ B
end = time.time()

print("Time taken with NumPy:", end - start, "seconds")


Time taken with NumPy: 4.892764568328857 seconds
